package com.itskidan.core_impl.database

import android.content.Context
import com.itskidan.core_api.ResourceManager
import com.itskidan.core_impl.R
import timber.log.Timber
import java.io.BufferedReader
import java.io.InputStreamReader
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class AppResourceManager @Inject constructor(
    private val context: Context
) : ResourceManager {

    override fun getCurrencyCodes(): List<String> {
        Timber.tag("MyLog").d("method: getCurrencyCodes()")
        val inputStream = context.resources.openRawResource(R.raw.available_currency_codes)
        val reader = BufferedReader(InputStreamReader(inputStream))
        return reader.useLines { it.toList() }
    }
    override fun getDefaultCurrencyName(): String =
        context.getString(R.string.unknown_currency_name)

    override fun getDefaultCurrencyFlag(): Int = R.drawable.unknown
    override fun getCurrencyNamesMap(): Map<String, String> {
        return mapOf(
            "AED" to context.getString(R.string.uae_dirham),
            "AFN" to context.getString(R.string.afghani),
            "ALL" to context.getString(R.string.lek),
            "AMD" to context.getString(R.string.armenian_dram),
            "ANG" to context.getString(R.string.netherlands_antillean_guilder),
            "AOA" to context.getString(R.string.kwanza),
            "ARS" to context.getString(R.string.argentine_peso),
            "AUD" to context.getString(R.string.australian_dollar),
            "AWG" to context.getString(R.string.aruban_florin),
            "AZN" to context.getString(R.string.azerbaijanian_manat),
            "BAM" to context.getString(R.string.convertible_mark),
            "BBD" to context.getString(R.string.barbados_dollar),
            "BDT" to context.getString(R.string.taka),
            "BGN" to context.getString(R.string.bulgarian_lev),
            "BHD" to context.getString(R.string.bahraini_dinar),
            "BIF" to context.getString(R.string.burundi_franc),
            "BMD" to context.getString(R.string.bermudian_dollar),
            "BND" to context.getString(R.string.brunei_dollar),
            "BOB" to context.getString(R.string.boliviano),
            "BOV" to context.getString(R.string.mvdol),
            "BRL" to context.getString(R.string.brazilian_real),
            "BSD" to context.getString(R.string.bahamian_dollar),
            "BTN" to context.getString(R.string.ngultrum),
            "BWP" to context.getString(R.string.pula),
            "BYN" to context.getString(R.string.belarussian_ruble),
            "BZD" to context.getString(R.string.belize_dollar),
            "CAD" to context.getString(R.string.canadian_dollar),
            "CDF" to context.getString(R.string.congolese_franc),
            "CHF" to context.getString(R.string.swiss_franc),
            "CLF" to context.getString(R.string.unidades_de_fomento),
            "CLP" to context.getString(R.string.chilean_peso),
            "CNY" to context.getString(R.string.yuan_renminbi),
            "COP" to context.getString(R.string.colombian_peso),
            "CRC" to context.getString(R.string.costa_rican_colon),
            "CUC" to context.getString(R.string.peso_convertible),
            "CUP" to context.getString(R.string.cuban_peso),
            "CVE" to context.getString(R.string.cape_verde_escudo),
            "CZK" to context.getString(R.string.czech_koruna),
            "DJF" to context.getString(R.string.djibouti_franc),
            "DKK" to context.getString(R.string.danish_krone),
            "DOP" to context.getString(R.string.dominican_peso),
            "DZD" to context.getString(R.string.algerian_dinar),
            "EGP" to context.getString(R.string.egyptian_pound),
            "ERN" to context.getString(R.string.nakfa),
            "ETB" to context.getString(R.string.ethiopian_birr),
            "EUR" to context.getString(R.string.euro),
            "FJD" to context.getString(R.string.fiji_dollar),
            "FKP" to context.getString(R.string.falkland_islands_pound),
            "GBP" to context.getString(R.string.pound_sterling),
            "GEL" to context.getString(R.string.lari),
            "GHS" to context.getString(R.string.ghana_cedi),
            "GIP" to context.getString(R.string.gibraltar_pound),
            "GMD" to context.getString(R.string.dalasi),
            "GNF" to context.getString(R.string.guinea_franc),
            "GTQ" to context.getString(R.string.quetzal),
            "GYD" to context.getString(R.string.guyana_dollar),
            "HKD" to context.getString(R.string.hong_kong_dollar),
            "HNL" to context.getString(R.string.lempira),
            "HRK" to context.getString(R.string.croatian_kuna),
            "HTG" to context.getString(R.string.gourde),
            "HUF" to context.getString(R.string.forint),
            "IDR" to context.getString(R.string.rupiah),
            "ILS" to context.getString(R.string.new_israeli_sheqel),
            "INR" to context.getString(R.string.indian_rupee),
            "IQD" to context.getString(R.string.iraqi_dinar),
            "IRR" to context.getString(R.string.iranian_rial),
            "ISK" to context.getString(R.string.iceland_krona),
            "JMD" to context.getString(R.string.jamaican_dollar),
            "JOD" to context.getString(R.string.jordanian_dinar),
            "JPY" to context.getString(R.string.yen),
            "KES" to context.getString(R.string.kenyan_shilling),
            "KGS" to context.getString(R.string.som),
            "KHR" to context.getString(R.string.riel),
            "KMF" to context.getString(R.string.comoro_franc),
            "KPW" to context.getString(R.string.north_korean_won),
            "KRW" to context.getString(R.string.won),
            "KWD" to context.getString(R.string.kuwaiti_dinar),
            "KYD" to context.getString(R.string.cayman_islands_dollar),
            "KZT" to context.getString(R.string.tenge),
            "LAK" to context.getString(R.string.kip),
            "LBP" to context.getString(R.string.lebanese_pound),
            "LKR" to context.getString(R.string.sri_lanka_rupee),
            "LRD" to context.getString(R.string.liberian_dollar),
            "LSL" to context.getString(R.string.loti),
            "LTL" to context.getString(R.string.lithuanian_litas),
            "LVL" to context.getString(R.string.latvian_lats),
            "LYD" to context.getString(R.string.libyan_dinar),
            "MAD" to context.getString(R.string.moroccan_dirham),
            "MDL" to context.getString(R.string.moldovan_leu),
            "MGA" to context.getString(R.string.malagasy_ariary),
            "MKD" to context.getString(R.string.denar),
            "MMK" to context.getString(R.string.kyat),
            "MNT" to context.getString(R.string.tugrik),
            "MOP" to context.getString(R.string.pataca),
            "MRO" to context.getString(R.string.ouguiya),
            "MUR" to context.getString(R.string.mauritius_rupee),
            "MVR" to context.getString(R.string.rufiyaa),
            "MWK" to context.getString(R.string.kwacha),
            "MXN" to context.getString(R.string.mexican_peso),
            "MYR" to context.getString(R.string.malaysian_ringgit),
            "MZN" to context.getString(R.string.mozambique_metical),
            "NAD" to context.getString(R.string.namibia_dollar),
            "NGN" to context.getString(R.string.naira),
            "NIO" to context.getString(R.string.cordoba_oro),
            "NOK" to context.getString(R.string.norwegian_krone),
            "NPR" to context.getString(R.string.nepalese_rupee),
            "NZD" to context.getString(R.string.new_zealand_dollar),
            "OMR" to context.getString(R.string.rial_omani),
            "PAB" to context.getString(R.string.balboa),
            "PEN" to context.getString(R.string.sol),
            "PGK" to context.getString(R.string.kina),
            "PHP" to context.getString(R.string.philippine_peso),
            "PKR" to context.getString(R.string.pakistan_rupee),
            "PLN" to context.getString(R.string.zloty),
            "PYG" to context.getString(R.string.guarani),
            "QAR" to context.getString(R.string.qatari_rial),
            "RON" to context.getString(R.string.new_romanian_leu),
            "RSD" to context.getString(R.string.serbian_dinar),
            "RUB" to context.getString(R.string.russian_ruble),
            "RWF" to context.getString(R.string.rwanda_franc),
            "SAR" to context.getString(R.string.saudi_riyal),
            "SBD" to context.getString(R.string.solomon_islands_dollar),
            "SCR" to context.getString(R.string.seychelles_rupee),
            "SDG" to context.getString(R.string.sudanese_pound),
            "SEK" to context.getString(R.string.swedish_krona),
            "SGD" to context.getString(R.string.singapore_dollar),
            "SHP" to context.getString(R.string.saint_helena_pound),
            "SLL" to context.getString(R.string.leone),
            "SOS" to context.getString(R.string.somali_shilling),
            "SRD" to context.getString(R.string.surinam_dollar),
            "SSP" to context.getString(R.string.south_sudanese_pound),
            "STD" to context.getString(R.string.dobra),
            "SVC" to context.getString(R.string.el_salvador_colon),
            "SYP" to context.getString(R.string.syrian_pound),
            "SZL" to context.getString(R.string.lilangeni),
            "THB" to context.getString(R.string.baht),
            "TJS" to context.getString(R.string.somoni),
            "TMT" to context.getString(R.string.turkmenistan_new_manat),
            "TND" to context.getString(R.string.tunisian_dinar),
            "TOP" to context.getString(R.string.pa_anga),
            "TRY" to context.getString(R.string.turkish_lira),
            "TTD" to context.getString(R.string.trinidad_and_tobago_dollar),
            "TWD" to context.getString(R.string.new_taiwan_dollar),
            "TZS" to context.getString(R.string.tanzanian_shilling),
            "UAH" to context.getString(R.string.hryvnia),
            "UGX" to context.getString(R.string.uganda_shilling),
            "USD" to context.getString(R.string.us_dollar),
            "UYU" to context.getString(R.string.peso_uruguayo),
            "UZS" to context.getString(R.string.uzbekistan_sum),
            "VEF" to context.getString(R.string.bolivar),
            "VND" to context.getString(R.string.dong),
            "VUV" to context.getString(R.string.vatu),
            "WST" to context.getString(R.string.tala),
            "XAF" to context.getString(R.string.cfa_franc_beac),
            "XCD" to context.getString(R.string.east_caribbean_dollar),
            "XOF" to context.getString(R.string.cfa_franc_bceao),
            "XPF" to context.getString(R.string.cfp_franc),
            "YER" to context.getString(R.string.yemeni_rial),
            "ZAR" to context.getString(R.string.rand),
            "ZMW" to context.getString(R.string.zambian_kwacha),
            "ZWL" to context.getString(R.string.zimbabwe_dollar)
        )
    }

    override fun getCurrencyFlagsMap(): Map<String, Int> {
        return mapOf(
            "AED" to R.drawable.aed,
            "AFN" to R.drawable.afn,
            "ALL" to R.drawable.all,
            "AMD" to R.drawable.amd,
            "ANG" to R.drawable.ang,
            "AOA" to R.drawable.aoa,
            "ARS" to R.drawable.ars,
            "AUD" to R.drawable.aud,
            "AWG" to R.drawable.awg,
            "AZN" to R.drawable.azn,
            "BAM" to R.drawable.bam,
            "BBD" to R.drawable.bbd,
            "BDT" to R.drawable.bdt,
            "BGN" to R.drawable.bgn,
            "BHD" to R.drawable.bhd,
            "BIF" to R.drawable.bif,
            "BMD" to R.drawable.bmd,
            "BND" to R.drawable.bnd,
            "BOB" to R.drawable.bob,
            "BOV" to R.drawable.bov,
            "BRL" to R.drawable.brl,
            "BSD" to R.drawable.bsd,
            "BTN" to R.drawable.btn,
            "BWP" to R.drawable.bwp,
            "BYN" to R.drawable.byn,
            "BZD" to R.drawable.bzd,
            "CAD" to R.drawable.cad,
            "CDF" to R.drawable.cdf,
            "CHF" to R.drawable.chf,
            "CLF" to R.drawable.clf,
            "CLP" to R.drawable.clp,
            "CNY" to R.drawable.cny,
            "COP" to R.drawable.cop,
            "CRC" to R.drawable.crc,
            "CUC" to R.drawable.cuc,
            "CUP" to R.drawable.cup,
            "CVE" to R.drawable.cve,
            "CZK" to R.drawable.czk,
            "DJF" to R.drawable.djf,
            "DKK" to R.drawable.dkk,
            "DOP" to R.drawable.dop,
            "DZD" to R.drawable.dzd,
            "EGP" to R.drawable.egp,
            "ERN" to R.drawable.ern,
            "ETB" to R.drawable.etb,
            "EUR" to R.drawable.eur,
            "FJD" to R.drawable.fjd,
            "FKP" to R.drawable.fkp,
            "GBP" to R.drawable.gbp,
            "GEL" to R.drawable.gel,
            "GHS" to R.drawable.ghs,
            "GIP" to R.drawable.gip,
            "GMD" to R.drawable.gmd,
            "GNF" to R.drawable.gnf,
            "GTQ" to R.drawable.gtq,
            "GYD" to R.drawable.gyd,
            "HKD" to R.drawable.hkd,
            "HNL" to R.drawable.hnl,
            "HRK" to R.drawable.hrk,
            "HTG" to R.drawable.htg,
            "HUF" to R.drawable.huf,
            "IDR" to R.drawable.idr,
            "ILS" to R.drawable.ils,
            "INR" to R.drawable.inr,
            "IQD" to R.drawable.iqd,
            "IRR" to R.drawable.irr,
            "ISK" to R.drawable.isk,
            "JMD" to R.drawable.jmd,
            "JOD" to R.drawable.jod,
            "JPY" to R.drawable.jpy,
            "KES" to R.drawable.kes,
            "KGS" to R.drawable.kgs,
            "KHR" to R.drawable.khr,
            "KMF" to R.drawable.kmf,
            "KPW" to R.drawable.kpw,
            "KRW" to R.drawable.krw,
            "KWD" to R.drawable.kwd,
            "KYD" to R.drawable.kyd,
            "KZT" to R.drawable.kzt,
            "LAK" to R.drawable.lak,
            "LBP" to R.drawable.lbp,
            "LKR" to R.drawable.lkr,
            "LRD" to R.drawable.lrd,
            "LSL" to R.drawable.lsl,
            "LTL" to R.drawable.ltl,
            "LVL" to R.drawable.lvl,
            "LYD" to R.drawable.lyd,
            "MAD" to R.drawable.mad,
            "MDL" to R.drawable.mdl,
            "MGA" to R.drawable.mga,
            "MKD" to R.drawable.mkd,
            "MMK" to R.drawable.mmk,
            "MNT" to R.drawable.mnt,
            "MOP" to R.drawable.mop,
            "MRO" to R.drawable.mro,
            "MUR" to R.drawable.mur,
            "MVR" to R.drawable.mvr,
            "MWK" to R.drawable.mwk,
            "MXN" to R.drawable.mxn,
            "MYR" to R.drawable.myr,
            "MZN" to R.drawable.mzn,
            "NAD" to R.drawable.nad,
            "NGN" to R.drawable.ngn,
            "NIO" to R.drawable.nio,
            "NOK" to R.drawable.nok,
            "NPR" to R.drawable.npr,
            "NZD" to R.drawable.nzd,
            "OMR" to R.drawable.omr,
            "PAB" to R.drawable.pab,
            "PEN" to R.drawable.pen,
            "PGK" to R.drawable.pgk,
            "PHP" to R.drawable.php,
            "PKR" to R.drawable.pkr,
            "PLN" to R.drawable.pln,
            "PYG" to R.drawable.pyg,
            "QAR" to R.drawable.qar,
            "RON" to R.drawable.ron,
            "RSD" to R.drawable.rsd,
            "RUB" to R.drawable.rub,
            "RWF" to R.drawable.rwf,
            "SAR" to R.drawable.sar,
            "SBD" to R.drawable.sbd,
            "SCR" to R.drawable.scr,
            "SDG" to R.drawable.sdg,
            "SEK" to R.drawable.sek,
            "SGD" to R.drawable.sgd,
            "SHP" to R.drawable.shp,
            "SLL" to R.drawable.sll,
            "SOS" to R.drawable.sos,
            "SRD" to R.drawable.srd,
            "SSP" to R.drawable.ssp,
            "STD" to R.drawable.std,
            "SVC" to R.drawable.svc,
            "SYP" to R.drawable.syp,
            "SZL" to R.drawable.szl,
            "THB" to R.drawable.thb,
            "TJS" to R.drawable.tjs,
            "TMT" to R.drawable.tmt,
            "TND" to R.drawable.tnd,
            "TOP" to R.drawable.top,
            "TRY" to R.drawable.resource_try,
            "TTD" to R.drawable.ttd,
            "TWD" to R.drawable.twd,
            "TZS" to R.drawable.tzs,
            "UAH" to R.drawable.uah,
            "UGX" to R.drawable.ugx,
            "USD" to R.drawable.usd,
            "UYU" to R.drawable.uyu,
            "UZS" to R.drawable.uzs,
            "VEF" to R.drawable.vef,
            "VND" to R.drawable.vnd,
            "VUV" to R.drawable.vuv,
            "WST" to R.drawable.wst,
            "XAF" to R.drawable.xaf,
            "XCD" to R.drawable.xcd,
            "XOF" to R.drawable.xof,
            "XPF" to R.drawable.xpf,
            "YER" to R.drawable.yer,
            "ZAR" to R.drawable.zar,
            "ZMW" to R.drawable.zmw,
            "ZWL" to R.drawable.zwl
        )
    }


}